services/build.gradle, web/build.gradle
Adding Jacoco reports so that we can measure coverage.
Jenkins build: https://jenkins.josdem.io/job/jmailer-spring-boot/22/
=> [small]feature/42

web/build.gradle, web/src/main/resources/templates/welcome.ftl
- Adding Vetlog welcome email template
=> [small]Feature/72

services/src/main/java/com/jos/dem/jmailer/service/FilterService.java, services/src/main/java/com/jos/dem/jmailer/service/impl/EmailValidatorServiceImpl.java, services/src/main/java/com/jos/dem/jmailer/service/impl/FilterServiceImpl.java, services/src/test/java/com/jos/dem/jmailer/service/EmailValidatorServiceTest.java, services/src/test/java/com/jos/dem/jmailer/service/FilterServiceTest.java, web/build.gradle
- Adding filter service to detect spam users by keyword
- Adding filter service logic to the email validator
- Updating tests cases
=> [small]Feature/75

services/build.gradle, services/src/main/java/com/josdem/jmailer/command/Command.java, services/src/main/java/com/josdem/jmailer/command/MessageCommand.java, services/src/main/java/com/josdem/jmailer/config/EmailProperties.java, services/src/main/java/com/josdem/jmailer/exception/BusinessException.java, services/src/main/java/com/josdem/jmailer/service/FilterService.java, services/src/main/java/com/josdem/jmailer/service/impl/EmailValidatorServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/FilterServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/MailServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/MessageServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/NotificationServiceImpl.java, services/src/test/java/com/josdem/jmailer/service/EmailServiceTest.java, services/src/test/java/com/josdem/jmailer/service/EmailValidatorServiceTest.java, services/src/test/java/com/josdem/jmailer/service/FilterServiceTest.java, services/src/test/java/com/josdem/jmailer/service/MailServiceTest.java, services/src/test/java/com/josdem/jmailer/service/MessageServiceTest.java, services/src/test/java/com/josdem/jmailer/service/NotificationServiceTest.java, web/build.gradle, web/src/main/java/com/josdem/jmailer/JmailerApplication.java, web/src/main/java/com/josdem/jmailer/advice/AfterThrowingAdvice.java, web/src/main/java/com/josdem/jmailer/config/ActiveMQConfig.java, web/src/main/java/com/josdem/jmailer/config/ApplicationProperties.java, web/src/main/java/com/josdem/jmailer/config/SwaggerConfig.java, web/src/main/java/com/josdem/jmailer/controller/EmailerController.java, web/src/main/java/com/josdem/jmailer/controller/HandlerException.java, web/src/main/java/com/josdem/jmailer/messengine/JmsMessageListener.java, web/src/test/java/com/josdem/jmailer/controller/IndexControllerTest.java
- Adding Spotless configuration
- Formatting services
- Formatting web
=> [small]Feature/78

web/build.gradle, web/src/main/resources/static/package.json, web/src/main/resources/templates/batch.html, web/src/main/resources/templates/command_line.html, web/src/main/resources/templates/contact.html, web/src/main/resources/templates/error.html, web/src/main/resources/templates/form.html, web/src/main/resources/templates/fragments/footer.html, web/src/main/resources/templates/index.html
- Updating [Bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/) to the latest version
- Updating all page components
=> [medium]Feature/16

services/src/main/java/com/josdem/jmailer/command/MessageCommand.java, web/build.gradle, web/src/main/java/com/josdem/jmailer/config/SwaggerConfig.java, web/src/main/java/com/josdem/jmailer/controller/EmailerController.java, web/src/main/resources/application.yml, web/src/test/java/com/josdem/jmailer/config/SwaggerConfigTest.java
- Adding Swagger server configuration
- Adding `@Schema` annotation
- Adding Swagger configuration test
=> [small]Feature/62

web/build.gradle.kts, web/src/main/resources/templates/command_line.html
- Adding OkHttp request code example
- Adding valid token note
- Setting release version 🎉
=> [small]Feature/25

web/build.gradle.kts, web/src/main/java/com/josdem/jmailer/controller/IndexController.java, web/src/main/resources/application.yml, web/src/main/resources/templates/contact.html, web/src/main/resources/templates/flyer.html, web/src/test/java/com/josdem/jmailer/controller/IndexControllerTest.java
- Adding flyer page to show an email sent successfully message
=> [small]Feature/85

services/src/main/java/com/josdem/jmailer/service/impl/EmailValidatorServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/MailServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/MessageServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/NotificationServiceImpl.java, web/build.gradle.kts
- Adding `var` keyword when possible in services
- Updarting version
=> [small]Feature/94

web/build.gradle.kts, web/src/main/java/com/josdem/jmailer/JmailerApplication.java, web/src/main/java/com/josdem/jmailer/config/ActiveMQConfig.java, web/src/main/java/com/josdem/jmailer/config/SwaggerConfig.java, web/src/main/java/com/josdem/jmailer/controller/HandlerException.java, web/src/main/java/com/josdem/jmailer/controller/IndexController.java, web/src/main/java/com/josdem/jmailer/messengine/JmsMessageListener.java
- Using `var` whenever possible in web module
=> [small]Feature/95

web/build.gradle.kts, web/src/main/resources/templates/index.html
- Adding expected `test-id` elements
=> [small]Feature/87

web/build.gradle.kts, web/src/main/resources/templates/command_line.html, web/src/main/resources/templates/form.html, web/src/main/resources/templates/index.html
=> [small]Feature/90

web/build.gradle.kts, web/src/main/resources/templates/batch.html
- Adding expected `test-id` locator
=> [small]Feature/92

web/build.gradle.kts, web/src/main/resources/templates/contact.html
- Adding `test-id` locators in register page
=> [small]Feature/89

services/build.gradle.kts, web/build.gradle.kts
- Updating all dependencies to the latest versions
- Setting release version 🎉
=> [small]Feature/88

services/src/main/java/com/josdem/jmailer/config/EmailProperties.java, web/build.gradle.kts, web/src/main/java/com/josdem/jmailer/config/ActiveMQConfig.java, web/src/main/java/com/josdem/jmailer/config/ApplicationConfig.java, web/src/main/java/com/josdem/jmailer/controller/EmailerController.java
- Using email configuration class to inject email properties
=> [small]Feature/108

services/src/main/java/com/josdem/jmailer/command/MessageCommand.java, services/src/main/java/com/josdem/jmailer/config/EmailProperties.java, services/src/main/java/com/josdem/jmailer/config/TemplateConfig.java, services/src/main/java/com/josdem/jmailer/model/Client.java, services/src/main/java/com/josdem/jmailer/service/impl/MailServiceImpl.java, services/src/test/java/com/josdem/jmailer/service/MailServiceTest.java, services/src/test/java/com/josdem/jmailer/service/NotificationServiceTest.java, web/src/main/resources/application.yml
Hello
Could you please review my solution of issue 129  and issue 134
Thank you
Best Regards
Zoli
=> Solution to issue 134 and 129

web/build.gradle.kts, web/src/main/resources/templates/adoption_es.ftl, web/src/main/resources/templates/forgotPassword_es.ftl
=> [small]Feature/130

.github/workflows/test.yml, services/build.gradle.kts, services/src/main/java/com/josdem/jmailer/config/TemplateConfig.java, web/build.gradle.kts
- Adding SonarCloud secret token
- Adding SonarCloud configuration
- Setting release version 🎉
=> [small]Feature/110

web/build.gradle.kts, web/src/main/resources/templates/forgotPassword_es.ftl, web/src/main/resources/templates/welcome_es.ftl
- Adding look & feel to the forgot password spanish version email template
- Adding extra format to the welcome spanish template
=> [small]Feature/142

web/build.gradle.kts, web/src/main/resources/templates/forgotPassword.ftl
- Translate forgot password to English
- Add Vetlog look and feel to the template
**Note:** This PR closes #146 and #141
=> [small]Feature/141

web/build.gradle.kts, web/src/main/resources/templates/adoption.ftl, web/src/main/resources/templates/forgotPassword.ftl
- Adding adoption template Vetlog look and feel 
- Translating to English
=> [small]Feature/139

services/src/main/java/com/josdem/jmailer/command/MessageCommand.java, services/src/main/java/com/josdem/jmailer/config/TemplateConfig.java, services/src/main/java/com/josdem/jmailer/model/Client.java, services/src/main/java/com/josdem/jmailer/service/impl/MailServiceImpl.java, services/src/main/java/com/josdem/jmailer/service/impl/NotificationServiceImpl.java, services/src/test/java/com/josdem/jmailer/service/MailServiceTest.java, services/src/test/java/com/josdem/jmailer/service/NotificationServiceTest.java, web/build.gradle.kts, web/src/main/resources/application.yml, web/src/main/resources/templates/command_line.html, web/src/main/resources/templates/contact.html, web/src/main/resources/templates/form.html, web/src/test/java/com/josdem/jmailer/service/NotificationServiceIntegrationTest.java
- Adding subject to `MessageCommand`
- Updating tests
=> [medium]Feature/148

services/build.gradle.kts, web/build.gradle.kts, web/src/main/java/com/josdem/jmailer/config/ApplicationConfig.java, web/src/main/java/com/josdem/jmailer/controller/EmailerController.java, web/src/main/java/com/josdem/jmailer/controller/HandlerExceptionResolverImpl.java
- Fixing maintainability issues reported by SonarCloud
=> [small]Feature/151

services/build.gradle.kts, web/build.gradle.kts
- Adding Jacoco configuration in services
=> [small]Feature/149

services/src/main/java/com/josdem/jmailer/config/EmailProperties.java, web/build.gradle.kts, web/src/main/java/com/josdem/jmailer/config/ActiveMQConfig.java, web/src/main/resources/application.yml
- Deleting unused data
- Setting trusted packages
=> [small]Feature/150

services/src/test/java/com/josdem/jmailer/config/TemplateConfigTest.java, services/src/test/java/com/josdem/jmailer/exception/BusinessExceptionTest.java, services/src/test/java/com/josdem/jmailer/service/MailServiceTest.java, web/build.gradle.kts
- Adding missing tests
- Coverage increased to 82%
**Screenshot**
=> [small]Feature/163

web/build.gradle.kts, web/src/main/resources/static/package.json, web/src/main/resources/templates/adoption.ftl, web/src/main/resources/templates/adoption_es.ftl, web/src/main/resources/templates/forgotPassword.ftl, web/src/main/resources/templates/forgotPassword_es.ftl, web/src/main/resources/templates/welcome.ftl, web/src/main/resources/templates/welcome_es.ftl
- Updating bootstrap to the latest version `5.3.3`
- Updating project version
=> [small]Feature/153
